version: 2
updates:
  - directory: "/"
    open-pull-requests-limit: 5
    package-ecosystem: "npm" 
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Tokyo"
  - directory: "/"
    open-pull-requests-limit: 5
    package-ecosystem: "github-actions" 
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Tokyo"
