name: Lint

on:
  push:
    paths:
      - "**.ts"
      - ".eslintrc.json"
      - "package.json"

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: " 13.x"
    - name: yarn install, and lint
      run: |
        yarn install
        yarn lint
      env:
        CI: true
