name: Lint

on:
  push:
    paths:
      - "**.ts"
      - ".eslintrc.json"
      - "package.json"
jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - name: npm install, and lint
      run: |
        npm install
        npm run lint
      env:
        CI: true
