name: Publish package

on:
    pull_request:
        branches:
            - master
        types: [closed]

jobs:
    publish:
        runs-on: ubuntu-18.04
        if: github.event.pull_request.merged == true
        steps:
            - name: Checkout source
              uses: actions/checkout@v2
            - name: Use Node.js "14.x"
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"
            - name: Install dependencies
              run: npm install
              env:
                  CI: true
            - name: Check availability
              id: check_availability
              run: $(npm bin)/can-npm-publish
              continue-on-error: true
            - name: Publish
              if: steps.check_availability.outcome == "success"
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
            - name: Post comment
              uses: mshick/add-pr-comment@v1
              if: steps.check_availability.outcome == "success"
              with:
                  message: |
                      Thank you for your contributions!
                      We publish new version of this package.
                      Cheers!
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  repo-token-user-login: "github-actions[bot]"
                  allow-repeats: false
            - name: Post comment
              uses: mshick/add-pr-comment@v1
              if: steps.check_availability.outcome == "failure"
              with:
                  message: |
                      Thank you for your contributions!
                      We include your contributions in next release.
                      Cheers!
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  repo-token-user-login: "github-actions[bot]"
                  allow-repeats: false
